media: images
content:
  - name: products
    label: "Products Catalog"
    file: "products.json"
    fields:
      - name: id
        label: "Product ID"
        type: string
      - name: name
        label: "Product Name"
        type: string
      - name: category
        label: "Category Name"
        type: string
      - name: price
        label: "Price"
        type: string
      - name: image
        label: "Product Image"
        type: image
