media: images
content:
  - name: products
    file: products.json
    fields:
      - name: id
        type: string
      - name: name
        type: string
      - name: category
        type: string
      - name: price
        type: string
      - name: image
        type: image
